sudo: required

language: shell

compiler:

arch:
  packages:
    - "jack2"
    - "alsa-utils" 
    - "systemd" 
    - "coreutils"
    - "python2"
  script:
    - "makepkg -i"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
